name: generate

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  pr-hooks:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        repo: ['mocoog/grpc-go-packages']
    steps:
      - uses: actions/checkout@v2
      - name: dispatch update-pb
        if: github.event.pull_request.merged == true
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: update-pb
          client-payload: '{"pr_title": "${{ github.event.pull_request.title }}"}'
